### PR TITLE
go.mod: update dependencies + drop custom kind node image

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Comment by mythi** [comment]
updated to v1.27.5 and rebased. this is ready for the release

**Review by fidencio — APPROVED** [review]
lgtm, thanks @mythi!

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @mythi

**Comment by fidencio** [comment]
TDX is failing, the failure is not related tot this PR, and I've opened https://github.com/confidential- containers/operator/issues/257 to track it.

**Pull request merged**
