### PR TITLE
remote: Add runtime class

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Add new kata-remote runtime class for peer pods configuration support

Fixes: #186

### CODE REVIEW

**Comment by wainersm** [comment]
Hi @stevenhorsman , I was wondering why you didn't change the config/samples/ccruntime/default/kustomization.yaml file but it is explained in the issue #186. You have opted for the first case, right?

I was also thinking that maybe we could have "kata-remote" and "kata-remote-caa" (the former defaulting to latest) because, in theory, we could have other remote implementations than CAA into the future. Or I am wrong and CAA is the only possible remote implementation?

**Comment by stevenhorsman** [comment]
> Hi @stevenhorsman , I was wondering why you didn't change the config/samples/ccruntime/default/kustomization.yaml file but it is explained in the issue #186. You have opted for the first case, right?

Yeah - in the absence of any feedback I figured the safest option was to keep it separate as it's easier to merge later than unpick

> I was also thinking that maybe we could have "kata-remote" and "kata-remote-caa" (the former defaulting to latest) because, in theory, we could have other remote implementations than CAA into the future. Or I am wrong and CAA is the only possible remote implementation?

Yeah, I'm not against this and have thought about it before. Again I picked `kata-remote` out of simplicity when I created the kata configuration files (which I think have to match the runtimeclass), but I'm not against renaming this after 0.5 - just trying to limit the number of changes going in late in the release.

That said, if you feel strongly about doing these now then I can try and rework them.

**Comment by wainersm** [comment]
> > Hi @stevenhorsman , I was wondering why you didn't change the config/samples/ccruntime/default/kustomization.yaml file but it is explained in the issue #186. You have opted for the first case, right?
> 
> Yeah - in the absence of any feedback I figured the safest option was to keep it separate as it's easier to merge later than unpick
> 

Got it!

> > I was also thinking that maybe we could have "kata-remote" and "kata-remote-caa" (the former defaulting to latest) because, in theory, we could have other remote implementations than CAA into the future. Or I am wrong and CAA is the only possible remote implementation?
> 
> Yeah, I'm not against this and have thought about it before. Again I picked `kata-remote` out of simplicity when I created the kata configuration files (which I think have to match the runtimeclass), but I'm not against renaming this after 0.5 - just trying to limit the number of changes going in late in the release.
>

It's fair.
 
> That said, if you feel strongly about doing these now then I can try and rework them.

Nope, let's keep it simple.

**Review by wainersm — APPROVED** [review]
Thanks @stevenhorsman

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Comment by stevenhorsman** [comment]
It looks like the CLH test did run and pass (http://jenkins.katacontainers.io/view/all/job/confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-clh-PR/118/), but didn't report back for whatever reason, I think it's safe to merge this based on that.

**Pull request merged**
