### PR TITLE
tests: Improve variable definition in tests/e2e scripts

### PR DESCRIPTION
**Pull request by GabyCT**
To have a better consistency across the test/e2e scripts this PR improves the variable definition by using local as a best practice.

### CODE REVIEW

**Review by ldoktor — APPROVED** [review]
Nice, it'd be nice to fix this issue across all shell scripts within repository (or at least directory). Are you interested in doing it (here or in a following PR), or do you want me to take care of that (I understand it's quite boring, but consistent :D)

**Comment by GabyCT** [comment]
@ldoktor let me do it

**Comment by GabyCT** [comment]
@ldoktor @wainersm changes applied

**Comment by ldoktor** [comment]
Looks good although I spotted a few variables in `operator.sh` in `wait_for_stabilization` function, could you please include them as well? (that should be all, I hope :-D)

**Comment by GabyCT** [comment]
@ldoktor thanks for the feedback, sorry that I missed those

**Review by ldoktor — APPROVED** [review]
Thank you for bearing with my nitpicks :-)

**Comment by GabyCT** [comment]
> Thank you for bearing with my nitpicks :-)

not worries, thanks for the feedback helps me to improve my work

**Review by portersrc — APPROVED** [review]

**Review by wainersm — COMMENTED** [review]
Thanks @GabyCT !

**Review by wainersm — APPROVED** [review]

**Pull request merged**
