### PR TITLE
Update CoCo artifacts to candidates for v0.7.0 release 

### PR DESCRIPTION
**Pull request by fitzthum**

### CODE REVIEW

**Comment by fitzthum** [comment]
Missed one thing. Will push again in a second.

**Comment by wainersm** [comment]
I'm working with @UnmeshDeodhar to debug the problem on snp.

**Comment by fitzthum** [comment]
So for s390x only the third test is failing? Is this a common case? Should we just try to retrigger? @stevenhorsman @BbolroC

**Comment by stevenhorsman** [comment]
> So for s390x only the third test is failing? Is this a common case? Should we just try to retrigger? @stevenhorsman @BbolroC

That's odd as that is the most basic test. I'll rebuild it

**Comment by UnmeshDeodhar** [comment]
SNP test is passing, but did not report: http://jenkins.katacontainers.io/job/confidential-containers-operator-main-ubuntu-20.04_snp-x86_64-containerd_kata-qemu-snp-PR/37/console

**Comment by stevenhorsman** [comment]
> SNP test is passing, but did not report: http://jenkins.katacontainers.io/job/confidential-containers-operator-main-ubuntu-20.04_snp-x86_64-containerd_kata-qemu-snp-PR/37/console

Yeah the s390x rebuild pass 6mins ago, but seems to be struggling to report too.

**Review by wainersm — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
LGTM!

**Pull request merged**
