### PR TITLE
docs: Fix misspelling on peer pods test document

### PR DESCRIPTION
**Pull request by GabyCT**
This PR fixes a misspelling on the peer pods test document.

### CODE REVIEW

**Comment by bpradipt** [comment]
> lgtm. A question to other reviewers, is it really necessary to run functional CI on this PR? We don't have the protection here and in this case I'd suggest skipping it...

It's not needed.. However I think some workflows will automatically run.

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by bpradipt** [comment]
However I don't know if there is a way to override the required tests via a label. May be @wainersm @stevenhorsman or @fidencio might know.

**Comment by ldoktor** [comment]
> However I don't know if there is a way to override the required tests via a label. May be @wainersm @stevenhorsman or @fidencio might know.

Ahh we do have the `required` set for them so no, they have to run... Anyway I tried :-)

**Pull request merged**
