### PR TITLE
do-not-merge: testing the handler for containerd <= 1.6

### PR DESCRIPTION
**Pull request by wainersm**

### CODE REVIEW

**Comment by ChengyuZhu6** [comment]
tdx test is passed: http://10.112.240.228:8080/job/confidential-containers-operator-main-centos8stream-x86_64-containerd_kata-qemu-tdx-PR/589/

**Comment by wainersm** [comment]
> tdx test is passed: http://10.112.240.228:8080/job/confidential-containers-operator-main-centos8stream-x86_64-containerd_kata-qemu-tdx-PR/589/

cool, thanks for letting me know @ChengyuZhu6 !

I'm debugging why it fails to start a container registry on Ubuntu 22.04; locally I can make it work just fine :(

**Comment by fidencio** [comment]
Closing as https://github.com/confidential-containers/operator/pull/274 has the patches provided here.
Thanks @wainersm!

**Pull request closed without merging**
