### PR TITLE
containerd: switch to the right gpg key url

### PR DESCRIPTION
**Pull request by Amulyam24**
The google url fails with an error of public key not available, hence switch it to the right one.

Fixes: #221

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Amulyam24!

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @Amulyam24

**Comment by wainersm** [comment]
hi @Amulyam24 ! Even with changing the gpg key we were having problems to get the packaged kubectl installed in the pre-install image. This way I proposed a different approach (please see https://github.com/confidential-containers/operator/commit/9f2f377171abf50247e6d109b27fe61febe2125d) that got merged today. Therefore, this PR is not needed anymore. Can I close it?

**Pull request closed without merging**
