### PR TITLE
install: Add cri-o paths

### PR DESCRIPTION
**Pull request by stevenhorsman**
Add host and mount path for cri-o

Fixes: #192

### CODE REVIEW

**Comment by stevenhorsman** [comment]
@bpradipt @jensfr @snir911 - I think this change is helpful to unify the ccruntime in the base coco operator and peer pods, but you will know better than me.

**Comment by snir911** [comment]
Seems right to me, thanks, cc @wainersm also

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @stevenhorsman

**Comment by stevenhorsman** [comment]
@arronwy @fidencio - if you could check TDX that would be great

**Review by wainersm — APPROVED** [review]

**Pull request merged**
