### PR TITLE
go.mod: update go-urn

### PR DESCRIPTION
**Pull request by fitzthum**
This should resolve our license failure.

Go-urn included the wrong license string in a previous release, but it has been removed.

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @fitzthum!

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by ldoktor — APPROVED** [review]
Looks good, one of the CI jobs failed with the occasional-to-be-seen failure where uninstall won't install. I don't think it's related to this change.

**Comment by ldoktor** [comment]
Well it failed in the same manner, either the s390x machine is misbehaving or there might actually be a problem with that version on it? @BbolroC any ideas? https://github.com/confidential-containers/operator/actions/runs/10236858387/job/28332541893?pr=405

**Comment by BbolroC** [comment]
> Member

Let me rerun the test and look into it. Thanks.

**Comment by BbolroC** [comment]
It turns out a golang version on the runner at the time of Ci failure (1.21.x) has an issue. The CI job went green with the latest golang (1.22.5). https://github.com/confidential-containers/operator/actions/runs/10246488905/job/28343684076?pr=406

But there was a dependency issue on `controller-gen` with the latest golang. We can merge #406 first and rebase/merge this one. Thanks.

**Pull request merged**
