### PR TITLE
fix: add support for imagePullPolicy for installer daemonsets (#395)

### PR DESCRIPTION
**Pull request by teodor-pripoae**
This PR implements support for ImagePullPolicy which is present in the CRD but not actually used (default Always).

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @teodor-pripoae!

**Review by beraldoleal — APPROVED** [review]
LGTM, thanks.

**Comment by bpradipt** [comment]
@stevenhorsman @fidencio would you be able to re-run the required tests for this PR?
This is ready to be merged, but pending since quite some time..

**Comment by stevenhorsman** [comment]
> @stevenhorsman @fidencio would you be able to re-run the required tests for this PR? This is ready to be merged, but pending since quite some time..

I've tried closing and re-opening, but it might need a rebase as the jobs have changes since then

**Comment by bpradipt** [comment]
@teodor-pripoae would you be able to rebase the PR? Sorry for the delay :-(

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by bpradipt** [comment]
Otoh, may be rebase is not needed. All required tests are passing and this can be merged..

**Pull request merged**
