### PR TITLE
pre-reqs: Bump reqs-payload image

### PR DESCRIPTION
**Pull request by stevenhorsman**
- After we updated to pick up nydus-snapshotter v0.3.13 in the pre-reqs image, start picking up this version.

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
LGTM

**Review by ldoktor — APPROVED** [review]
This does cover all of the places although the commit message is a bit cryptical (maybe because I'm not native). Something like `pre-reqs image had been recently updated to use nydus-snapshotter v0.3.13, use that version in our sample configs.` would be IMO clearer, what do you think? (again, I'm not native)

**Comment by stevenhorsman** [comment]
> This does cover all of the places although the commit message is a bit cryptical (maybe because I'm not native). Something like `pre-reqs image had been recently updated to use nydus-snapshotter v0.3.13, use that version in our sample configs.` would be IMO clearer, what do you think? (again, I'm not native)

That's fair - Wainer recently accused my commit messages of sounding like they were AI generated, so I need to work on that!

**Comment by stevenhorsman** [comment]
> This does cover all of the places although the commit message is a bit cryptical (maybe because I'm not native). Something like `pre-reqs image had been recently updated to use nydus-snapshotter v0.3.13, use that version in our sample configs.` would be IMO clearer, what do you think? (again, I'm not native)

@ldoktor - I hope this update is clearer? If not - let me know!

**Pull request merged**
