### PR TITLE
docs: Remove INSTALL-CC-WITH-IBM-SE.md

### PR DESCRIPTION
**Pull request by BbolroC**
As the documentation has been migrated to the confidential-containers repo, (see https://github.com/confidential-containers/confidential-containers/pull/241) this commit removes the migrated installation guide for IBM SE.

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]

**Review by ldoktor — COMMENTED** [review]
Could you please also modify the https://github.com/confidential-containers/operator/blob/main/docs/INSTALL.md?plain=1#L173 link to point to https://github.com/confidential-containers/confidential-containers/blob/main/guides/ibm-se.md ?

**Comment by BbolroC** [comment]
> Could you please also modify the https://github.com/confidential-containers/operator/blob/main/docs/INSTALL.md?plain=1#L173 link to point to https://github.com/confidential-containers/confidential-containers/blob/main/guides/ibm-se.md ?

Thanks for the catch. The PR has been updated. 👍

**Review by ldoktor — APPROVED** [review]
thanks, lgtm

**Comment by ldoktor** [comment]
Well it's not a blip, it's because the `ccruntime e2e tests for PR` have `paths-ignore: docs/**`... Which is logical, but stock github requirements do not cope with that.

**Comment by ldoktor** [comment]
... perhaps the operator needs something like https://github.com/kata-containers/kata-containers/pull/9637 as well ;-)

**Comment by stevenhorsman** [comment]
> ... perhaps the operator needs something like [kata-containers/kata-containers#9637](https://github.com/kata-containers/kata-containers/pull/9637) as well ;-)

Yes, I didn't realise we had that skip here as well as in kata (which we had to remove as it forced us to admin push PRs like this.

**Pull request merged**
