### PR TITLE
Use consistent yaml file extension

### PR DESCRIPTION
**Pull request by portersrc**

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Normally convention is that we start our commit headers with the components/area being updated e.g. `ci: ...`, or `workflows: ...`, but it's not mandatory and enforced, so doesn't block merging.

**Comment by GabyCT** [comment]
lgtm

**Review by fitzthum — APPROVED** [review]

**Review by ldoktor — APPROVED** [review]
lgtm although you might have also included the `tests/e2e/ansible/*.yml` files as well ;-)

**Comment by portersrc** [comment]
> LGTM. Normally convention is that we start our commit headers with the components/area being updated e.g. `ci: ...`, or `workflows: ...`, but it's not mandatory and enforced, so doesn't block merging.

I'll start doing this, then. "Components/area" seems to be a loose term based on what I've seen people doing, but best effort is still an improvement.

**Comment by portersrc** [comment]
> lgtm although you might have also included the `tests/e2e/ansible/*.yml` files as well ;-)

Hey say less

**Review by ldoktor — COMMENTED** [review]
Thank you, Chris, this seems to cover all yaml files, only the README.md containes 2 more references of yml workflows that needs to be addressed. As for the `kube-flannel.yml`, I think it would be better to include it as well (including all the files where it's referenced) but I don't say it's a must have.

**Comment by wainersm** [comment]
Thanks @portersrc ! Now we just sit and wait someone send a PR to switch back to .yml ;)

**Comment by portersrc** [comment]
> Now we just sit and wait someone send a PR to switch back to .yml ;)

Yes lol; I'd be fine with that as long as it's consistent.

> the README.md containes 2 more references

Thank you! That was sloppy of me.

> As for the kube-flannel.yml, I think it would be better to include it as well

OK, giving it a shot.

**Review by ldoktor — APPROVED** [review]
lgtm, let's see whether the pipeline failure was just a glitch...

**Comment by ldoktor** [comment]
still looks good, I can see 2 previous acks so let me get this in ;-)

**Pull request merged**
