### PR TITLE
tests:e2e: Install kustomize from the Go source code

### PR DESCRIPTION
**Pull request by GabyCT**
This PR installs the kustomize CLI from source in order to avoid the random failures due to the Github Actions rate limitations.

### CODE REVIEW

**Comment by GabyCT** [comment]
@ldoktor please check this PR, I've test it locally and seems to be working

**Review by ldoktor — COMMENTED** [review]
Looks good, let's see how it behaves in the CI.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Review by ldoktor — APPROVED** [review]
Thanks, works well on my computer, works well in the currently working CI, lets get this in.

**Pull request merged**
