### PR TITLE
fix: migrate from k8s.gcr.io to registry.k8s.io

### PR DESCRIPTION
**Pull request by CIPHERTron**
This fix is a part of an umbrella issue https://github.com/kubernetes/k8s.io/issues/4780

### CODE REVIEW

**Comment by fidencio** [comment]
@CIPHERTron, please, squash all the commits into a single one and force-push to the same branch.

**Comment by CIPHERTron** [comment]
> @CIPHERTron, please, squash all the commits into a single one and force-push to the same branch.

Done! @fidencio Lmk if there are any more changes.

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @CIPHERTron

**Review by fidencio — APPROVED** [review]
lgtm, thanks @CIPHERTron!

**Comment by wainersm** [comment]
Hi @CIPHERTron !

This PR breaks our CI because it seems that registry.k8s.io does not contain `registry.k8s.io/coredns:v1.8.6`. We install k8s with kubeadm, what else should be changed to pull the right coredns image?

**Comment by fidencio** [comment]
Thanks for checking this out, @wainersm!

**Comment by katexochen** [comment]
Hey, I've digged a bit into this issue. The problem @wainersm mentioned isn't caused by the change of the container registry. Actually, `k8s.gcr.io` and `registry.k8s.io` contain the same images:

```sh
❯ crane ls registry.k8s.io/coredns # or `crane ls k8s.gcr.io/coredns`
...
1.2.2
1.2.3
1.2.4
1.2.6
1.3.0
1.3.1
1.5.0
1.6.2
1.6.5
1.6.6
1.6.7
1.7.0
```

But the coredns images were moved to `coredns/coredns` :

```sh
❯ crane ls registry.k8s.io/coredns/coredns # or `crane ls k8s.gcr.io/coredns/coredns`
sha256-017727efcfeb7d053af68e51436ce8e65edbc6ca573720afb4f79c8594036955.sig
sha256-8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a.sig
sha256-a0ead06651cf580044aeb0a0feba63591858fb2e43ade8c9dea45a6a89ae7e5e.sig
sha256-b82e294de6be763f73ae71266c8f5466e7e03c69f3a1de96efd570284d35bb18.sig
v1.10.0
v1.10.1
v1.6.6
v1.6.7
v1.6.9
v1.7.0
v1.7.1
v1.8.0
v1.8.3
v1.8.4
v1.8.5
v1.8.6
v1.9.3
v1.9.4
```

**Comment by wainersm** [comment]
> Hey, I've digged a bit into this issue. The problem @wainersm mentioned isn't caused by the change of the container registry. Actually, `k8s.gcr.io` and `registry.k8s.io` contain the same images:
> 
> ```shell
> ❯ crane ls registry.k8s.io/coredns # or `crane ls k8s.gcr.io/coredns`
> ...
> 1.2.2
> 1.2.3
> 1.2.4
> 1.2.6
> 1.3.0
> 1.3.1
> 1.5.0
> 1.6.2
> 1.6.5
> 1.6.6
> 1.6.7
> 1.7.0
> ```
> 
> But the coredns images were moved to `coredns/coredns` :
> 
> ```shell
> ❯ crane ls registry.k8s.io/coredns/coredns # or `crane ls k8s.gcr.io/coredns/coredns`
> sha256-017727efcfeb7d053af68e51436ce8e65edbc6ca573720afb4f79c8594036955.sig
> sha256-8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a.sig
> sha256-a0ead06651cf580044aeb0a0feba63591858fb2e43ade8c9dea45a6a89ae7e5e.sig
> sha256-b82e294de6be763f73ae71266c8f5466e7e03c69f3a1de96efd570284d35bb18.sig
> v1.10.0
> v1.10.1
> v1.6.6
> v1.6.7
> v1.6.9
> v1.7.0
> v1.7.1
> v1.8.0
> v1.8.3
> v1.8.4
> v1.8.5
> v1.8.6
> v1.9.3
> v1.9.4
> ```

Would bump to k8s 1.26.0 fix that? Or perhaps we should be passing the registry and let kubeadm uses its default.

**Comment by katexochen** [comment]
> Would bump to k8s 1.26.0 fix that? Or perhaps we should be passing the registry and let kubeadm uses its default.

@wainersm Sorry, I'm not sure what exactly the initial issue was or where this is configured in the fist place. The logs of the CI runs don't exist anymore.

**Comment by katexochen** [comment]
Well this code seems to be gone anyway. https://github.com/search?q=repo%3Aconfidential-containers%2Fcloud-api-adaptor%20k8s.gcr.io&type=code
But there is a CSI IBM patch with the old registry.

**Pull request closed without merging**
