### PR TITLE
payloads: Update kata-containers / enclave-cc payloads for the v0.5.0 release

### PR DESCRIPTION
**Pull request by fidencio**
SSIA

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks

**Review by wainersm — APPROVED** [review]
0.5, almost there!

**Comment by fidencio** [comment]
I had to force push, as I missed updating `config/release/kustomization.yaml`

**Review by mythi — APPROVED** [review]
+1

**Pull request merged**
