### PR TITLE
Update payloads for v0.9.0-alpha0

### PR DESCRIPTION
**Pull request by fitzthum**
The payloads for v0.9.0-alpha

@stevenhorsman or @BbolroC can you guys confirm that we do not need the s390x suffix for the s390x CRD?

### CODE REVIEW

**Comment by fitzthum** [comment]
enclave-cc tests seems to be failing cc @mythi 

note that we jumped from the v0.8.0 tag to the v0.9.0 tag (rather than using latest), so I don't think [this job](https://github.com/confidential-containers/operator/actions/workflows/enclave-cc-cicd.yaml) has been testing any of the more recent changes.

**Comment by stevenhorsman** [comment]
Hey @fitzthum, are you talking about the
```
nameSuffix: -s390x
```
in the s390x kustomization.yaml?

or on the kata-deploy image tag: `quay.io/kata-containers/kata-deploy:3.4.0-s390x`? If it's the latter then I think I can confirm. A couple of releases ago we switch the kata payload to be multi-arch, so there shouldn't be any problems there and the tests should confirm it on this PR

**Comment by fitzthum** [comment]
enclave-cc issue has been resolved thanks to @portersrc 

@confidential-containers/operator-maintainers PTAL so we can finish the release

**Comment by portersrc** [comment]
The [enclave-cc fix](https://github.com/confidential-containers/operator/pull/368/files#diff-f114572e4fad1f5877f35afa33a12b9ee133f8318ba26a74818f1c31c08a857cR69) looks OK for the moment, but it would be good for @mythi to take a look later (e.g. his recent commit message [here](https://github.com/confidential-containers/operator/commit/61726a799ba91ee29e6ca945ccad9de620b98ec1) suggests he may have a better long-term idea for this).

@stevenhorsman , do you know if we need to update [this line](https://github.com/fitzthum/operator/blob/bump090/config/manager/kustomization.yaml#L16) yet? I see you were active here when we swapped [0.8.0 back to latest](https://github.com/fitzthum/operator/commit/81a89f9fff01d5678043115ed40c43437d7adee6). I assume it needs to be set to 0.9.0-alpha0 at some point.

@bpradipt , do you have thoughts on needed changes for v0.9.0-alpha0 release [here](https://github.com/confidential-containers/operator/blob/main/config/overlays/peerpods/crd/kustomization.yaml#L5C3-L6)? Also, is `src` missing in that resource path, e.g. something like `github.com/confidential-containers/cloud-api-adaptor/-->src<--/peerpodconfig-ctrl/config/crd`?ref=v0.8.0`

This [ssh-demo case](https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/ssh-demo/kustomization.yaml#L10-L13) is odd. I would ignore. Technically I think reqs-payload should be for this release, but I don't know if that's even tested (or maybe it's part of the CI?).

**Comment by stevenhorsman** [comment]
> @stevenhorsman , do you know if we need to update [this line](https://github.com/fitzthum/operator/blob/bump090/config/manager/kustomization.yaml#L16) yet? I see you were active here when we swapped [0.8.0 back to latest](https://github.com/fitzthum/operator/commit/81a89f9fff01d5678043115ed40c43437d7adee6). I assume it needs to be set to 0.9.0-alpha0 at some point.

Last release it was updated as part of the operator hub piece: https://github.com/confidential-containers/operator/commit/2a05696e4149425c84d0279171d8048e0835ec36#diff-14effe9ea1a3ddb6e419e627a3501a6c42aa2dcbc76803923e9aff2438e6ee34 and as it is referencing the operator image release tag which we haven't cut I don't think it can be done now.

> This [ssh-demo case](https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/ssh-demo/kustomization.yaml#L10-L13) is odd. I would ignore. Technically I think reqs-payload should be for this release, but I don't know if that's even tested (or maybe it's part of the CI?).

Tobin has created a discussion to remove it https://github.com/confidential-containers/operator/issues/370, but if we aren't doing it for this release (and I think it's probably too late for that), then I think we just bump it, but nobody is testing it, and I don't think it is considered supported.

**Review by portersrc — APPROVED** [review]
Thanks @stevenhorsman for clearing some doubts. Looks OK to me now.

**Comment by fitzthum** [comment]
I think for this release we may forego the operator hub bit anyway since it is an alpha release and Wainer is on vacation.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @fitzthum!

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by mythi** [comment]
> The [enclave-cc fix](https://github.com/confidential-containers/operator/pull/368/files#diff-f114572e4fad1f5877f35afa33a12b9ee133f8318ba26a74818f1c31c08a857cR69) looks OK for the moment, but it would be good for @mythi to take a look later (e.g. his recent commit message [here](https://github.com/confidential-containers/operator/commit/61726a799ba91ee29e6ca945ccad9de620b98ec1) suggests he may have a better long-term idea for this).

apologies, I had completely missed this. I can get things properly fixed once the release is out (essentially just getting the test/e2e/ yamls updated.)

**Pull request merged**
