### PR TITLE
Release: Update payloads for v0.11.0

### PR DESCRIPTION
**Pull request by niteeshkd**

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
LGTM

ptal @stevenhorsman @wainersm or other @confidential-containers/operator-maintainers

**Review by mythi — APPROVED** [review]
LGTM

**Review by wainersm — APPROVED** [review]
Hi @niteeshkd , thanks for this! LGTM.

It would be nice if we could get @portersrc 's https://github.com/confidential-containers/operator/pull/452 merged, so to ease the release process.

**Comment by wainersm** [comment]
This addresses step 4 and 5 of release checklist: https://github.com/confidential-containers/confidential-containers/issues/269 . Let's get it merged.

**Pull request merged**
