### PR TITLE
Release: Revert v0.9.0 release-specfic changes back to dev values

### PR DESCRIPTION
**Pull request by niteeshkd**
This reverts the changes done in two commits (related to the kata payloads and enclave-cc payloads) with the PR #397 .

### CODE REVIEW

**Comment by ldoktor** [comment]
Looks good, how about the https://github.com/confidential-containers/operator/pull/397/commits/d51c1e4ecf4b92ac8509111b1a4ca25ea5e27c14 shouldn't it be tagged to the next alpha to keep the release-required changes together?

**Comment by niteeshkd** [comment]
> Looks good, how about the [d51c1e4](https://github.com/confidential-containers/operator/commit/d51c1e4ecf4b92ac8509111b1a4ca25ea5e27c14) shouldn't it be tagged to the next alpha to keep the release-required changes together?

I am not sure whether [d51c1e4](https://github.com/confidential-containers/operator/commit/d51c1e4ecf4b92ac8509111b1a4ca25ea5e27c14) should be tagged to next alpha ( as it might mean that we already know the requirements for that alpha release) but may be we could tag it to latest (similar to tags for others).  
@fitzthum - any suggestion ?

**Review by fidencio — APPROVED** [review]
lgtm, thanks @niteeshkd!

**Review by ryansavino — APPROVED** [review]
LGTM

**Pull request merged**
