### PR TITLE
ccruntime: Update Kata Containers to the v0.3.0 payload release

### PR DESCRIPTION
**Pull request by fidencio**
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@BbolroC, mind to take a look on what's going on with the s390x CI?

**Comment by BbolroC** [comment]
> @BbolroC, mind to take a look on what's going on with the s390x CI?

I think that it was just hiccups from the artifact source.

**Review by jensfr — APPROVED** [review]
lgtm, thank you @fidencio

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
