### PR TITLE
install/pre-install: Update containerd

### PR DESCRIPTION
**Pull request by stevenhorsman**
Update containerd version now we have a new release

### CODE REVIEW

**Review by zvonkok — APPROVED** [review]
LGTM Thanks!

**Review by jepio — APPROVED** [review]

**Comment by wainersm** [comment]
I am trying to get https://github.com/confidential-containers/operator/pull/179 merged first. Let's wait a little bit, end of the day maybe.

**Comment by wainersm** [comment]
> Given that #179 hasn't been merged we aren't actually testing the pre-install image, so any failures aren't related to the change

I've faced issues to merge #179. So I opened https://github.com/confidential-containers/operator/pull/226 in order to test this PR.

Lifted the do-not-merge label.

**Comment by wainersm** [comment]
@stevenhorsman https://github.com/confidential-containers/containerd/releases/tag/v1.6.8.2 is missing the s390x build. That's why the jobs on https://github.com/confidential-containers/operator/pull/226 (that I am using to test this PR) are failing.

**Comment by wainersm** [comment]
btw, @stevenhorsman , https://github.com/confidential-containers/operator/pull/226/commits/cf3aaef619d2597c2f00e37fcc7f6a28982605ea fixes a bunch of troubles I've faced to get kubectl installed on the pre-install image. If you and @jepio agree, could we pick up that fix on this PR too?

**Comment by stevenhorsman** [comment]
> @stevenhorsman https://github.com/confidential-containers/containerd/releases/tag/v1.6.8.2 is missing the s390x build. That's why the jobs on #226 (that I am using to test this PR) are failing.

Sorry, that's my bad. I must've removed it when updating the containerd workflow as it's only in 1.7, not 1.6. I will look at that right now.

**Comment by stevenhorsman** [comment]
> > @stevenhorsman https://github.com/confidential-containers/containerd/releases/tag/v1.6.8.2 is missing the s390x build. That's why the jobs on #226 (that I am using to test this PR) are failing.
> 
> Sorry, that's my bad. I must've removed it when updating the containerd workflow as it's only in 1.7, not 1.6. I will look at that right now.

Fixed and the release re-built

**Comment by wainersm** [comment]
> > @stevenhorsman https://github.com/confidential-containers/containerd/releases/tag/v1.6.8.2 is missing the s390x build. That's why the jobs on #226 (that I am using to test this PR) are failing.
> 
> Sorry, that's my bad. I must've removed it when updating the containerd workflow as it's only in 1.7, not 1.6. I will look at that right now.

I forgive you @stevenhorsman . This time only ;)

**Review by wainersm — APPROVED** [review]
I think we can disregard the sev failure on https://github.com/confidential-containers/operator/pull/226 and proceed to merge here. Once the new pre-install image is built then we will have the opportunity to test it on sev too.

**Pull request merged**
