### PR TITLE
cli tool to change containerd config

### PR DESCRIPTION
**Pull request by mkulke**

### CODE REVIEW

**Comment by fidencio** [comment]
@mkulke, one thing that's been crossing my mind is whether we need a new tool for this or whether we'd be good enough relying on `tomlq` for this as we did on the Kata Containers side.

I'd like to know your opinion on this,

**Comment by mkulke** [comment]
> @mkulke, one thing that's been crossing my mind is whether we need a new tool for this or whether we'd be good enough relying on `tomlq` for this as we did on the Kata Containers side.
> 
> I'd like to know your opinion on this,

as said above, it doesn't matter whether you use a library or a cli tool, but if you want to have some confidence in what is happening, i.e. write tests and handle all those potential errors properly, this is probably easier to do in a dedicated tool.

a simple tomlq invocation will just handle the happy path, the rest you have to code (or opt to ignore) in bash

**Comment by fidencio** [comment]
> a simple tomlq invocation will just handle the happy path, the rest you have to code (or opt to ignore) in bash

Fair enough! :-)

**Comment by fidencio** [comment]
@mkulke: https://github.com/containerd/nydus-snapshotter/pull/570

**Pull request closed without merging**
