### PR TITLE
config: add kata-qemu-sev runtimeclass

### PR DESCRIPTION
**Pull request by Alex-Carter01**
Adding runtimeclass for sev. 

Depends on sev kata PRs:

- Packaging for initrd: https://github.com/kata-containers/kata-containers/pull/5120
- Packaging for OVMF: https://github.com/kata-containers/kata-containers/pull/5026
- Packaging for SEV-capable kernel + kernel module https://github.com/kata-containers/kata-containers/pull/5038
- Add agent config to rootfs: https://github.com/kata-containers/kata-containers/pull/5024
- Use depmod in rootfs builder on kernel module(s): https://github.com/kata-containers/kata-containers/pull/5127
- Kata-deploy add kata-qemu-sev shim/runtimeclas https://github.com/kata-containers/kata-containers/pull/5130

Integration testing of all of the SEV components has been successful. Made a cc bundle with all of the PRs added to base CCv0, converted to a docker container via the kata-deploy-cc docker script, and deployed to quay. Was able to run a pod after being deployed with the operator.

@fidencio @fitzthum @wainersm 

Signed-off-by: Alex Carter <Alex.Carter@ibm.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@Alex-Carter01, I'd hold this one and when updating the payload to a payload that does have support for the SEV work, then we add this one together with that.

WDYT?

**Comment by wainersm** [comment]
> @Alex-Carter01, I'd hold this one and when updating the payload to a payload that does have support for the SEV work, then we add this one together with that.
> 
> WDYT?

Sound as a good plan to me.

**Comment by Alex-Carter01** [comment]
> @Alex-Carter01, I'd hold this one and when updating the payload to a payload that does have support for the SEV work, then we add this one together with that.
> 
> WDYT?

Sure, makes sense, will wait until kata changes are merged and bundle updated.

**Comment by Alex-Carter01** [comment]
> @Alex-Carter01 looks like all the related PRs are merged. Can you please update this PR with the new payload image in addition to the SEV runtimeclasses ?

Alright, I updated the image commit to Steve's from yesterday that includes all of the sev PRs.

**Comment by wainersm** [comment]
Just published on Jenkins a job to test on SEV: http://jenkins.katacontainers.io/job/confidential-containers-operator-main-ubuntu-20.04_sev-x86_64-containerd_kata-qemu-sev-PR/

Let me run for the first time... fingers crossed:

/test-kata-qemu-sev

**Comment by wainersm** [comment]
oopppsss I missed one change on jenkins side...

**Comment by wainersm** [comment]
ok, second tentative...

/test-kata-qemu-sev

**Comment by bpradipt** [comment]
Let me try now ;) 
/test-kata-qemu-sev

**Comment by wainersm** [comment]
ok, almost there... the first executions failed because I realize we got two SEV machines on the pool, which is good, but the one being used by this job was a old one that we install a long time ago and it has kube-api-server running on it. I am not sure if that machine is actually assigned to another work. I am in touch with AMD team to figure that out.

Now I managed to run on the right machine, the new problem is that go is not found on PATH; I am looking on how to solve it.

**Comment by wainersm** [comment]
Finally passing! \o/

**Comment by bpradipt** [comment]
@Alex-Carter01 can you please rebase your PR.

**Comment by Alex-Carter01** [comment]
Rebased to now just add the kata-qemu-sev runtimeclass name with the now current linebreak. No longer needs to update the runtime payload since that is already steve's 77176cd7

**Comment by wainersm** [comment]
oh my, go not being found on PATH again... that's why the sev job failed

**Comment by wainersm** [comment]
Hopefully the sev job is fixed by explicitly using /bin/bash: https://github.com/kata-containers/ci/pull/496

/test-kata-qemu-sev

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @Alex-Carter01

**Pull request merged**
