### PR TITLE
actions: enable arm64 images for operator

### PR DESCRIPTION
**Pull request by huoqifeng**
Added arm64 images build for operator and it's pre-reqs payload

### CODE REVIEW

**Review by stevenhorsman — COMMENTED** [review]
Hey @huoqifeng - just to confirm the scope of this PR. This is adding arm64 archs to the multi-arch container images for the operator and pre-reqs image, but I don't think that the kata-deploy payload for arm64 builds the confidential features (notably the confidential image), so I'm not expecting it to work yet?

**Comment by huoqifeng** [comment]
> Hey @huoqifeng - just to confirm the scope of this PR. This is adding arm64 archs to the multi-arch container images for the operator and pre-reqs image, but I don't think that the kata-deploy payload for arm64 builds the confidential features (notably the confidential image), so I'm not expecting it to work yet?

@stevenhorsman yes, I understand and will use separate PR for the remains.

**Comment by seungukshin** [comment]
Some e2e test may fail because arcitecture is not set properly for arm64. The following change would be needed.
```diff
diff --git a/tests/e2e/ansible/group_vars/all b/tests/e2e/ansible/group_vars/all
index 3a78652..b9a6eb6 100644
--- a/tests/e2e/ansible/group_vars/all
+++ b/tests/e2e/ansible/group_vars/all
@@ -34,4 +34,7 @@ test_pkgs:
     - jq
   centos:
     - jq
-target_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
+binaries_architecture:
+  x86_64: amd64
+  aarch64: arm64
+target_arch: "{{ binaries_architecture[ansible_architecture] | default(ansible_architecture) }}"
```

**Comment by huoqifeng** [comment]
> Some e2e test may fail because arcitecture is not set properly for arm64. The following change would be needed.
> 
> ```diff
> diff --git a/tests/e2e/ansible/group_vars/all b/tests/e2e/ansible/group_vars/all
> index 3a78652..b9a6eb6 100644
> --- a/tests/e2e/ansible/group_vars/all
> +++ b/tests/e2e/ansible/group_vars/all
> @@ -34,4 +34,7 @@ test_pkgs:
>      - jq
>    centos:
>      - jq
> -target_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
> +binaries_architecture:
> +  x86_64: amd64
> +  aarch64: arm64
> +target_arch: "{{ binaries_architecture[ansible_architecture] | default(ansible_architecture) }}"
> ```

Thank you @seungukshin for the nice finding, I lost it as the PR CI seems did not pick the test run. Fixed it by applied your patch!

**Review by seungukshin — APPROVED** [review]
LGTM. Thank you @huoqifeng!

**Comment by huoqifeng** [comment]
@confidential-containers/operator-maintainers may you please help kick the PR test job?

**Review by ldoktor — APPROVED** [review]
Thanks, builds well although I noticed our e2e testing always builds all archs, which should be IMO changed to save some time. Anyway it's not related to this PR so I'd say it's good to go.

**Comment by ldoktor** [comment]
And it runs e2e on aarch64 well as well. Unfortunately IIRC we don't have the enterprise GH account so we can't enable it on arm just yet, right?

As for the functional testing, I do not have arm machine with KVM support handy so I just tried install/reinstall/uninstall only.

Overall let's get this in so people can start experimenting and let's discuss the potential e2e tests optimization elsewhere...

**Pull request merged**
