### PR TITLE
Go back to latest payloads after release

### PR DESCRIPTION
**Pull request by fitzthum**
The release is done, so let's go back to the upstream bundles for enclave-cc, kata, and reqs-deploy

### CODE REVIEW

**Review by ldoktor — COMMENTED** [review]
Hello @fitzthum, wouldn't it be clearer to use `git revert` as you are effectively reverting the 9d14530afece97840799a5b0e2fb8e18fd2a1056 f36b294d2d7b701505ae9f00b2f5a9c833aa0019 and actually even aa2706048c0fcd29c0191627de82c8b0f1b51118 ? I think doing so would be a nice practice in the future.

**Comment by fitzthum** [comment]
> Hello @fitzthum, wouldn't it be clearer to use git revert as you are effectively reverting the https://github.com/confidential-containers/operator/commit/9d14530afece97840799a5b0e2fb8e18fd2a1056 https://github.com/confidential-containers/operator/commit/f36b294d2d7b701505ae9f00b2f5a9c833aa0019 and actually even https://github.com/confidential-containers/operator/commit/aa2706048c0fcd29c0191627de82c8b0f1b51118 ? I think doing so would be a nice practice in the future.

I was thinking about this, but it seemed weird to revert the fairly old change for enclave-cc (we forgot to update those on the last release). I don't really have a preference either way. You might want to comment on https://github.com/confidential-containers/confidential-containers/pull/210 where we are fixing up the release checklist for next time. I think we will probably start using a script to make these changes in the future as well.

**Review by wainersm — APPROVED** [review]
I also liked the `git revert` idea. Maybe next release we can update the files so that it's git revert-able.

**Review by fidencio — CHANGES_REQUESTED** [review]
@fitzthum, the PR itself is not wrong, but it'll need a follow-up commit (as part of the very same PR).

Once we revert to use the latest from kata-containers, Operator jobs will break, as on the Kata Containers side a change was made but not reflected here, and it's my fault, see:
* https://github.com/kata-containers/kata-containers/blob/9a6d8d83308870ca662b1b811b1bb7c42b96cfba/tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml#L61-L62
* https://github.com/kata-containers/kata-containers/blob/9a6d8d83308870ca662b1b811b1bb7c42b96cfba/tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml#L77-L79

That mount has to be propagated here:
* https://github.com/confidential-containers/operator/blob/0e8b344e01e85b09684baee0392aa553395f24a7/config/samples/ccruntime/base/ccruntime.yaml#L18-L43

Thanks, and let me know if you face any issue updating the file.

**Comment by fitzthum** [comment]
Added the host mount.

I don't want this PR to become a catch-all for changes we pick up from Kata. Ideally it should be merged immediately after the release.

**Comment by fidencio** [comment]
> I don't want this PR to become a catch-all for changes we pick up from Kata. Ideally it should be merged immediately after the release.

I agree, but if the tests were not passing, we fix the minimum enough to get the CI green (which is the case at this point).

**Review by fidencio — APPROVED** [review]
lgtm, thanks @fitzthum!

**Pull request merged**
