### PR TITLE
Release: Update nydus snapshotter version

### PR DESCRIPTION
**Pull request by portersrc**
This is updated to match the nydus snapshotter version (v0.13.14) from the v3.9.0 kata release.

This is needed for v0.10.0 release process.

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. FYI there was some motivation to pick up a newer release of nydus-snapshotter in 3.9.0, but it doesn't seem very likely now.

**Comment by portersrc** [comment]
> there was some motivation to pick up a newer release of nydus-snapshotter in 3.9.0

If kata v3.9.0 ends up picking up a different nydus, I'll update this PR, then.

**Review by ldoktor — APPROVED** [review]
LGTM

**Comment by portersrc** [comment]
kata v3.9.0 is released [here](https://github.com/kata-containers/kata-containers/releases/tag/3.9.0), and it stuck with nydus v0.13.14 (see [here](https://github.com/kata-containers/kata-containers/blob/3.9.0/versions.yaml#L327-L330)).

This should be fine to merge now, and we can continue with v0.10.0 release for coco.

**Pull request merged**
