### PR TITLE
Release: Revert v0.11.0 release-specfic changes back to dev values

### PR DESCRIPTION
**Pull request by niteeshkd**
This reverts the changes done in two commits (related to the kata payloads and enclave-cc payloads) with the PR #465 .

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
`LGTM`

**Comment by fitzthum** [comment]
Some test issues 

```
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.31.1" Control plane version: "1.30.1"
```

**Comment by wainersm** [comment]
sorry @niteeshkd , I missed the discussion why we are reverting, mind to summarize to me?

**Comment by wainersm** [comment]
> > I missed the discussion why we are reverting, mind to summarize to me?
> 
> step 9 on release checklist. normal procedure but hopefully we didn't get ahead of ourselves

oh, just noticed the 0.10. version is out! hehehe sorry guys!

**Review by wainersm — APPROVED** [review]

**Pull request merged**
