### PR TITLE
containerd: add support to build and publish payload image for ppc64le

### PR DESCRIPTION
**Pull request by Amulyam24**

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Amulyam24

/cc @jensfr @bpradipt

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @Amulyam24

**Comment by Amulyam24** [comment]
Hi @bpradipt @fidencio, anything pending to merge this PR? Will this be on hold until [the ppc64le platform support PR](https://github.com/confidential-containers/operator/pull/218) gets merged? Please let me know your thoughts.

**Comment by Amulyam24** [comment]
Shall re-open this once operator image for ppc64le PR is merged which is dependent on kata payload image.

**Pull request closed without merging**
