### PR TITLE
config: Update to the latest CI payloads

### PR DESCRIPTION
**Pull request by fidencio**
Let's bump to the latest CI payloads and make sure those are and will continue to be passing the CI till we release the Operator at some point soon.

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @fidencio

**Comment by fidencio** [comment]
> Some of the tests timed out at scenario 15?

That's a test to uninstall the operator, and yep, I've noticed that's hanging even before the updates we've done.
See: https://github.com/confidential-containers/operator/pull/160, for instance.

**Comment by jepio** [comment]
Test 15 is failing, because post-install-daemon fails:
```
confidential-containers-system   cc-operator-post-uninstall-daemon-vf96h           0/1     CrashLoopBackOff   11 (4m4s ago)   35m
```

Log output is short and ends after "Restarting contianerd".

**Comment by jepio** [comment]
The failure is caused by an orphaned `/opt/confidential-containers/runtime-rs`, fix here: https://github.com/kata-containers/kata-containers/pull/6397. The `rmdir` in `post-uninstall.sh` is failing because coreutils logic is weird in v8.22: https://github.com/coreutils/coreutils/blob/v8.22/src/rmdir.c#L101-L107

**Comment by fidencio** [comment]
@UnmeshDeodhar, @ryansavino, @fitzthum, mind to take a look at the failures we're having on SEV?

**Comment by fitzthum** [comment]
I think we might need https://github.com/confidential-containers/operator/pull/159

@ryansavino @UnmeshDeodhar wdyt?

**Comment by fidencio** [comment]
I am really not sure what's going on with Jenkins, as it's not being triggered for any job here.
/cc @wainersm

**Comment by wainersm** [comment]
> I am really not sure what's going on with Jenkins, as it's not being triggered for any job here. /cc @wainersm

It usually happens when the queue is too big, but it seems not the case. I noticed a bunch of bare-metal machines are offline, something seems wrong with Jenkins.

**Comment by jepio** [comment]
I'm seeing this in buildlogs (http://jenkins.katacontainers.io/view/all/job/confidential-containers-operator-main-ubuntu-20.04_sev-x86_64-containerd_kata-qemu-sev-PR/187/console)
```
org.kohsuke.github.HttpException: {"message":"`confidential-containers` forbids access via a personal access token (classic). Please use a GitHub App, OAuth App, or a personal access token with fine-grained permissions.","documentation_url":"https://docs.github.com/rest/commits/statuses#create-a-commit-status"}
```

**Comment by fitzthum** [comment]
Oh, I did adjust the org settings for classic personal access tokens yesterday. I don't think I changed anything there, but let me double check.

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by wainersm** [comment]
> Oh, I did adjust the org settings for classic personal access tokens yesterday. I don't think I changed anything there, but let me double check.
> 
> Classic PAT are enabled now (I don't think they were in the past, but maybe). Is this a requirement of jenkins? It would be good to switch to fine-grained ones.

What I know is that jobs read permissions from the project/org to allow/disallow members/non-members of running/not-running.

**Pull request merged**
