### PR TITLE
config: update operator to use release tags for enclave-cc and kata

### PR DESCRIPTION
**Pull request by portersrc**
This covers step 19 from the release checklist [here](https://github.com/confidential-containers/confidential-containers/issues/145)

### CODE REVIEW

**Comment by portersrc** [comment]
The runtime-payload bundles didn't get created due to mishaps in the CI (see [here](https://github.com/kata-containers/kata-containers/actions/runs/6803330401/job/18525097560) and [here](https://github.com/kata-containers/kata-containers/actions/runs/6813321555)). Nevertheless, the v0.8.0 tag was already applied for ` 8de1f8e` (see [here](https://github.com/kata-containers/kata-containers/releases/tag/CC-0.8.0)), and the runtime-payload-ci kata-container bundles are correctly built for it. This is convenient enough, as we can just stick with this hash for the release.

Note this means that the fix from @littlejawa's [PR 8400](https://github.com/kata-containers/kata-containers/commit/8de1f8e19f858134ba455a7c04edcb21d8bcf6b1) is part of v0.8.0 (good), but @fidencio's [PR 8415](https://github.com/kata-containers/kata-containers/commit/6c2a2a14fe78d513e36eee8c6be14e39b009891d) to tweak the workflow is not (which should be OK, as we're moving off of those files soon).

Before merging, we probably want @wainersm's [operator fix](https://github.com/confidential-containers/operator/pull/284), and then the reqs-payload will need to be updated a final time here.

**Comment by fidencio** [comment]
@portersrc, we don't need to wait for @wainersm's fixes, to be honest, that can come later, **but before the release**.
I'll merge this one as soon as all CIs are green.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @portersrc!
/cc @stevenhorsman @bpradipt @wainersm for a review

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Review by wainersm — APPROVED** [review]
hi @portersrc ,

I liked the comment that you left on the commit:
```
Note: This intentionally uses the runtime-payload-ci hash for this release
due to issues creating the runtime-payload bundles.
```

LGTM.

**Pull request merged**
