### PR TITLE
Add kata-qemu-snp runtime class

### PR DESCRIPTION
**Pull request by jepio**
Following the example of kata-qemu-sev, add kata-qemu-snp where needed. This will result in a runtime class being defined and kata-deploy.sh configuring containerd and shim for kata-qemu-snp.

Fixes: kata-containers/kata-containers#6547

Depends on all the other PRs listed in #146

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
I only grep'ed for `kata-qemu-sev` and found only those places to change.

**Comment by wainersm** [comment]
@jepio would you like me to add a do-not-merge label to hold this until the remaining pieces aren't merged?

**Comment by jepio** [comment]
yes please :)

**Comment by fitzthum** [comment]
Time to revisit this? @jepio

**Comment by fitzthum** [comment]
Since there is no SNP test, we probably don't want to add to this release. In the short term if people want to use SNP they'll have to dig it out as an experimental feature by making the changes in this PR manually to their CR yaml.

**Comment by fidencio** [comment]
> Since there is no SNP test, we probably don't want to add to this release. In the short term if people want to use SNP they'll have to dig it out as an experimental feature by making the changes in this PR manually to their CR yaml.

Yep, this will be part of the next release when the SNP tests come.

It's good to remember, although orthogonal to this PR, that the SNP tests should and would be following the tests that other platforms are following, instead of build up atop of the current SEV tests, as we discussed in a meeting a few months ago.

**Comment by ryansavino** [comment]
@jepio my bad, didn't see this. I duplicated these changes in #197.

**Comment by fidencio** [comment]
Let me close this one as another PR with the same content was merged.

**Pull request closed without merging**
