### PR TITLE
Bump tags for release v0.6.0

### PR DESCRIPTION
**Pull request by fitzthum**
Update the payloads and the tag for the operator. 

Note the change to the enclave-cc sim payload. Is this correct? @mythi

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM assuming we can get confirmation that SIM using cc-kbc is okay

**Comment by fitzthum** [comment]
We are going to cut a new release of enclave-cc. I will update this PR when it is ready.

**Comment by fitzthum** [comment]
PR has been rebased with new enclave-cc payloads.

**Review by Xynnn007 — APPROVED** [review]
I checked that all the tags/hashes are matched.

**Comment by Xynnn007** [comment]
We should rerun the test here, while do not have the access.

**Pull request merged**
