### PR TITLE
enclave-cc: fix HW kustomization

### PR DESCRIPTION
**Pull request by mythi**
The 'images' key was missing and resulted in

error: invalid Kustomization: yaml: line 8: did not find expected key

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @mythi!

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by fidencio** [comment]
SEV didn't trigger, as this patch only affects enclave-cc I'm going ahead and merging it.

**Pull request merged**
