### PR TITLE
actions: build and publish operator for ppc64le platform

### PR DESCRIPTION
**Pull request by Amulyam24**

### CODE REVIEW

**Comment by Amulyam24** [comment]
Hi @bpradipt, PTAL!

Also a quick question - is there a plan to update the dependencies such as operator-sdk, golang etc. ? The k8s api version is 0.26.1 which is not quite aligned with the current sdk version.

**Comment by bpradipt** [comment]
@Amulyam24 It's a simple change and looks good from operator standpoint.
However I'm not sure if the rest of the pieces (the payloads) are available for ppc64le.
cc @stevenhorsman and @fidencio for their comments and next step.

**Comment by stevenhorsman** [comment]
> @Amulyam24 It's a simple change and looks good from operator standpoint. However I'm not sure if the rest of the pieces (the payloads) are available for ppc64le. cc @stevenhorsman and @fidencio for their comments and next step.

Yes - the kata runtime payload (see the `cc-payload` workflows in https://github.com/kata-containers/kata-containers/tree/CCv0/.github/workflows) are only built for amd64 and s390x, so we'll need that for power as well before the operator is useful.

**Comment by Amulyam24** [comment]
Hi @bpradipt @stevenhorsman. I'm aware of the dependency of the operator on the `runtime-payload`. For now, the only component needed for Power would be `cc-shim-v2`(considering running the peerpods approach) and this would need the support for cross-building the component as github actions don't support `ppc64le` runner by default.

There is an open PR that adds [support for cross-building kata components on non-x86](https://github.com/kata-containers/kata-containers/pull/6586). Once this is merged, I plan to have the runtime-payload published for `ppc64le` as well. 
For testing purposes, I'm using locally built images.

**Comment by bpradipt** [comment]
> The k8s api version is 0.26.1 which is not quite aligned with the current sdk version.
Yes. please check https://github.com/confidential-containers/operator/issues/163

**Comment by Amulyam24** [comment]
Hi @bpradipt @stevenhorsman, are we dependent on the kata runtime payload for ppc64le to be published officially for this PR to be merged or are we okay with merging this support and working on getting the payload image published? Please let me know your thoughts.

**Comment by stevenhorsman** [comment]
> Hi @bpradipt @stevenhorsman, are we dependent on the kata runtime payload for ppc64le to be published officially for this PR to be merged or are we okay with merging this support and working on getting the payload image published? Please let me know your thoughts.

I'm not sure if it makes must sense to publish the operator image for `ppc64le`, when there isn't a `ppc64le` kata payload image that it uses and I think that might just get confusing, so we'd want to get the kata-payload (and kata-deploy) support in first?

**Comment by Amulyam24** [comment]
Shall re-open this once the payload image is available for ppc64le.

**Pull request closed without merging**
