### PR TITLE
config: Update deps to v0.4.0 release

### PR DESCRIPTION
**Pull request by fidencio**
As part of v0.4.0 release we're bringing in the following images:
* kata-containers-129e43d1ea5cca528b7b97234b7561219208a244-x86_64
* kata-containers-129e43d1ea5cca528b7b97234b7561219208a244-s390x
* enclave-cc-HW-v0.4.0
* enclave-cc-SIM-v0.4.0

### CODE REVIEW

**Review by mythi — APPROVED** [review]
+1 for `enclave-cc`

**Comment by fidencio** [comment]
On the QEMU TDX CI
```
09:16:56 # Mar 06 16:15:01 tdx-ci kata[2340164]: time="2023-03-06T16:15:01.882711677+08:00" level=error msg="agent pull image err. rpc error: code = Internal desc = failed to pull manifest Registry error: url https://registry-1.docker.io/v2/katadocker/ssh-demo-eaa-kbc/manifests/latest, envelope: OCI API errors: [OCI API error: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit]" name=containerd-shim-v2 pid=2340164 sandbox=4bae6ccd60c16d345f5aab0ce68c77d75f055bdcf9d03b59450607ef0d1b3df7 source=virtcontainers subsystem=kata_agent
```

And we'll wait. :-)

**Review by stevenhorsman — APPROVED** [review]
LGTM and the kata-containers commit matches the latest on CCv0. Thanks!

**Pull request merged**
