### PR TITLE
GHA: Remove {pre,post}-action steps for self-hosted runners

### PR DESCRIPTION
**Pull request by BbolroC**
The following hooks:

- ACTIONS_RUNNER_HOOK_JOB_STARTED
- ACTIONS_RUNNER_HOOK_JOB_COMPLETED

could perfectly replace the existing {pre,post}-action scripts and will make a workflow independent of the runner context. This PR wipes out all GHA steps where the actions are triggered.

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

@AdithyaKrishnan please let me know when the runner for SEV/SNP is ready for this. I will ask for review when you guys are ready. Thanks.

### CODE REVIEW

**Review by ldoktor — APPROVED** [review]
Yep, those env variables seems to do exactly that so once the workers are configured it should be fine removing them here (as far as the `{pre,post}_action.sh` does not require some extra knowledge about the PR that wouldn't be available in the hooks but I think that shouldn't be the case, rigth?)

**Comment by BbolroC** [comment]
> Yep, those env variables seems to do exactly that so once the workers are configured it should be fine removing them here (as far as the `{pre,post}_action.sh` does not require some extra knowledge about the PR that wouldn't be available in the hooks but I think that shouldn't be the case, rigth?)

Yes, `{pre,post}_action.sh` does not depend on the workflow context. So it would be fine to simply remove them from the workflow. Thanks.

**Comment by AdithyaKrishnan** [comment]
@BbolroC AMD SEV and SNP Coco runners are ready. Please go ahead

**Review by AdithyaKrishnan — APPROVED** [review]
LGTM

**Review by fitzthum — APPROVED** [review]
LGTM

**Pull request merged**
