### PR TITLE
Add privileged label to the install namespace

### PR DESCRIPTION
**Pull request by bpradipt**
Fixes:#213

### CODE REVIEW

**Comment by bpradipt** [comment]
@fidencio @stevenhorsman ptal

**Comment by bpradipt** [comment]
Rebased the code to the latest

**Review by jensfr — APPROVED** [review]
lgtm, thank you @bpradipt

**Comment by bpradipt** [comment]
@stevenhorsman The SNP test doesn't seem to work. Can we merge this ?

**Comment by stevenhorsman** [comment]
> @stevenhorsman The SNP test doesn't seem to work. Can we merge this ?

SNP is still WIP, so shouldn't block anything. Whether we merge it now depends if it should be in, or out of the release.

**Comment by bpradipt** [comment]
> > @stevenhorsman The SNP test doesn't seem to work. Can we merge this ?
> 
> SNP is still WIP, so shouldn't block anything. Whether we merge it now depends if it should be in, or out of the release.

For the next release, let's have the SNP as not mandatory so that we don't unnecessarily wait for CI to pass and delay merging. Anyway forced merging was also available which we should have used. Lost opportunity :-( 

We did discuss in the last call to have this PR merged so that people installing from operator hub can do it without any issues. But now may not be the right time and anyone installing from operator hub will be required to manually label the namespace.

Anyways let's hold this and get back to it after the release is cut.

**Comment by stevenhorsman** [comment]
> For the next release, let's have the SNP as not mandatory so that we don't unnecessarily wait for CI to pass and delay merging.

Hey Pradipta, I might be missing something, but the SNP tests aren't required, so I don't think it blocks merging? Or maybe I have admin rights so I don't see that? If snp is showing as mandatory then it shouldn't be, so we need to ensure that doesn't happen again!

**Comment by stevenhorsman** [comment]
Given that we've cut the release, I guess we can merge this now? especially if we want to do a special operator hub v0.6.1 we should do it sooner rather than later?

**Comment by fitzthum** [comment]
Yeah let's merge as soon as the tests are good.

**Pull request merged**
