### PR TITLE
Update artifacts to v0.7.0 release bundles

### PR DESCRIPTION
**Pull request by fitzthum**
These are the bundles corresponding to the v0.7.0 tags for CCv0 and enclave-cc. 

Step 23 or https://github.com/confidential-containers/confidential-containers/issues/111

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
The runtime-payload was generated by the workflow: https://github.com/kata-containers/kata-containers/actions/runs/5626077123

**Comment by wainersm** [comment]
The s390x job fail:
```
18:44:01 [init] Using Kubernetes version: v1.24.0
18:44:01 [preflight] Running pre-flight checks
18:44:01 error execution phase preflight: [preflight] Some fatal errors occurred:
18:44:01 	[ERROR Port-6443]: Port 6443 is in use
18:44:01 [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

It suggests that a previous job did not clean up the node correctly. @BbolroC could you please have a look?

**Comment by BbolroC** [comment]
I've placed a clean-up code in the jenkins job. A port 6443 should be closed before the test starts. But it seems the 3rd test `Test can pull an unencrypted image inside the guest` is failing. I have no idea for why. It is over midnight in my place. I will have a look at the test next Monday. 😉

**Comment by BbolroC** [comment]
Good news, the 3rd test has passed when I run the test on another node. I think this has something to do with an infra. Let's see if the whole test ends up with going green.

**Review by stevenhorsman — APPROVED** [review]
LGTM

**Pull request merged**
