### PR TITLE
config: Revert "config: Remove kata-qemu-se"

### PR DESCRIPTION
**Pull request by BbolroC**
This reverts commit bfba38f90a1cfe35de6053e6cebf1ec0d8ee2b1f. This will fix a test failure at http://jenkins.katacontainers.io/job/confidential-containers-operator-main-ubuntu-20.04-s390x-SE-daily/

Fixes: #300

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
@BbolroC - I think you might want to revert https://github.com/confidential-containers/operator/commit/63fa8b02e386188bf3cbe78af41c8bdf57e1a8f2 too?

**Comment by BbolroC** [comment]
> @BbolroC - I think you might want to revert [63fa8b0](https://github.com/confidential-containers/operator/commit/63fa8b02e386188bf3cbe78af41c8bdf57e1a8f2) too?

Oh, yes. I missed it. Thanks for pointing it out.

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks

**Comment by stevenhorsman** [comment]
@BbolroC - DCO sign-off failing on the 2nd commit

**Comment by BbolroC** [comment]
I am working on fixing the CI failure on s390x.

**Comment by BbolroC** [comment]
@stevenhorsman  It looks the check `tests-e2e-ubuntu-20.04-x86_64-containerd_kata-clh` has been never fetched by Jenkins. I've checked the corresponding job http://jenkins.katacontainers.io/view/all/job/confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-clh-PR/ was disabled yesterday. Why don't we take it out of the list?

**Review by wainersm — APPROVED** [review]
thanks @BbolroC !

**Pull request merged**
