### PR TITLE
config: remove ssh-demo

### PR DESCRIPTION
**Pull request by fitzthum**
Following from https://github.com/confidential-containers/operator/issues/370 

I think we'll need to cleanup a few things in the docs as well (see https://github.com/confidential-containers/confidential-containers/pull/211)

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
It's always a joy seeing old unmaintained stuffs getting out. Thanks @fitzthum !

**Review by ldoktor — APPROVED** [review]
Yep, seems to cover all mentionings of ssh-demo here. Wainer, is your blog post updated, can we merge this?

**Comment by wainersm** [comment]
Hi @ldoktor !

> Yep, seems to cover all mentionings of ssh-demo here. Wainer, is your blog post updated, can we merge this?

On the blog post https://www.redhat.com/en/blog/how-use-confidential-containers-without-confidential-hardware luckily It points to a tagged file, so this removal is fine.

**Comment by ldoktor** [comment]
> Hi @ldoktor !
> 
> > Yep, seems to cover all mentionings of ssh-demo here. Wainer, is your blog post updated, can we merge this?
> 
> On the blog post https://www.redhat.com/en/blog/how-use-confidential-containers-without-confidential-hardware luckily It points to a tagged file, so this removal is fine.

Thanks for the confirmation. Shouldn't the https://github.com/confidential-containers/confidential-containers/tree/main/demos/ssh-demo be removed too? (which would require the blog to be updated as well...)

**Comment by fitzthum** [comment]
>  Shouldn't the https://github.com/confidential-containers/confidential-containers/tree/main/demos/ssh-demo be removed too? 

No. See commit message.

**Pull request merged**
