### PR TITLE
release: changes to publish 0.10.0 in operator hub

### PR DESCRIPTION
**Pull request by portersrc**
I submitted the https://github.com/k8s-operatorhub/community-operators/pull/5081 to publish 0.10.0 bundle in operator hub. After it is merged, coco's operator landing page in hub should get updated (see https://operatorhub.io/operator/cc-operator).

Here I'm sending the changes I did to publish it.

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
@portersrc thanks for working on this too!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @portersrc!

**Comment by ldoktor** [comment]
@portersrc I'm not sure if this can be merged already or if it should wait for https://github.com/k8s-operatorhub/community-operators/pull/5081 ?

**Comment by wainersm** [comment]
Hi @ldoktor !

> @portersrc I'm not sure if this can be merged already or if it should wait for [k8s-operatorhub/community-operators#5081](https://github.com/k8s-operatorhub/community-operators/pull/5081) ?

Usually I wait the PR to community-operators get merged first. I just ping'ed Jens to approve it. And I will send a commit there to add myself as an owner of the operator on the hub to speed up the release process.

**Pull request merged**
